"""Initial migration.

Revision ID: 09fbc1988da9
Revises: 
Create Date: 2021-03-22 10:19:18.237455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fbc1988da9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drink', sa.Column('description', sa.String(length=180), nullable=True))
    op.add_column('drink', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'drink', ['description'])
    op.add_column('ingredient', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('menu_crepe', sa.Column('description', sa.String(length=180), nullable=True))
    op.add_column('menu_crepe', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'menu_crepe', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_crepe', type_='unique')
    op.drop_column('menu_crepe', 'is_active')
    op.drop_column('menu_crepe', 'description')
    op.drop_column('ingredient', 'is_active')
    op.drop_constraint(None, 'drink', type_='unique')
    op.drop_column('drink', 'is_active')
    op.drop_column('drink', 'description')
    # ### end Alembic commands ###
