"""Initial migration

Revision ID: 9888c6604560
Revises: 
Create Date: 2021-03-15 16:00:15.145962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9888c6604560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'coffee_flavor_syrup', ['id'])
    op.create_unique_constraint(None, 'coffee_flavor_syrup_serving_size', ['id'])
    op.create_unique_constraint(None, 'coffee_name', ['id'])
    op.create_unique_constraint(None, 'coffee_temperature', ['id'])
    op.create_unique_constraint(None, 'crepe', ['id'])
    op.create_unique_constraint(None, 'crepe_flavor_profile', ['id'])
    op.create_unique_constraint(None, 'crepe_origination', ['id'])
    op.create_unique_constraint(None, 'drink', ['id'])
    op.create_unique_constraint(None, 'drink_category', ['id'])
    op.create_unique_constraint(None, 'drink_serving_size', ['id'])
    op.create_unique_constraint(None, 'espresso', ['serving_size'])
    op.create_unique_constraint(None, 'ice_cream_flavor', ['id'])
    op.create_unique_constraint(None, 'ice_cream_serving_size', ['id'])
    op.create_unique_constraint(None, 'ingredient', ['id'])
    op.create_unique_constraint(None, 'ingredient_category', ['id'])
    op.create_unique_constraint(None, 'ingredient_serving_size', ['id'])
    op.create_unique_constraint(None, 'milk', ['id'])
    op.create_unique_constraint(None, 'order', ['id'])
    op.create_unique_constraint(None, 'settings', ['id'])
    op.create_unique_constraint(None, 'side', ['id'])
    op.create_unique_constraint(None, 'side_name', ['id'])
    op.create_unique_constraint(None, 'side_type', ['id'])
    op.create_unique_constraint(None, 'stripe', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stripe', type_='unique')
    op.drop_constraint(None, 'side_type', type_='unique')
    op.drop_constraint(None, 'side_name', type_='unique')
    op.drop_constraint(None, 'side', type_='unique')
    op.drop_constraint(None, 'settings', type_='unique')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_constraint(None, 'milk', type_='unique')
    op.drop_constraint(None, 'ingredient_serving_size', type_='unique')
    op.drop_constraint(None, 'ingredient_category', type_='unique')
    op.drop_constraint(None, 'ingredient', type_='unique')
    op.drop_constraint(None, 'ice_cream_serving_size', type_='unique')
    op.drop_constraint(None, 'ice_cream_flavor', type_='unique')
    op.drop_constraint(None, 'espresso', type_='unique')
    op.drop_constraint(None, 'drink_serving_size', type_='unique')
    op.drop_constraint(None, 'drink_category', type_='unique')
    op.drop_constraint(None, 'drink', type_='unique')
    op.drop_constraint(None, 'crepe_origination', type_='unique')
    op.drop_constraint(None, 'crepe_flavor_profile', type_='unique')
    op.drop_constraint(None, 'crepe', type_='unique')
    op.drop_constraint(None, 'coffee_temperature', type_='unique')
    op.drop_constraint(None, 'coffee_name', type_='unique')
    op.drop_constraint(None, 'coffee_flavor_syrup_serving_size', type_='unique')
    op.drop_constraint(None, 'coffee_flavor_syrup', type_='unique')
    # ### end Alembic commands ###
